INSERT INTO categories (slug, name, icon, color) VALUES ('engineering-technology', 'Engineering & Technology', 'gear', 'bg-blue-soft text-blue');
INSERT INTO categories (slug, name, icon, color) VALUES ('medical-healthcare', 'Medical & Healthcare', 'steth', 'bg-pink-soft text-pink');
INSERT INTO categories (slug, name, icon, color) VALUES ('science-research', 'Science & Research', 'flask', 'bg-green-soft text-green');
INSERT INTO categories (slug, name, icon, color) VALUES ('commerce-finance', 'Commerce & Finance', 'chart', 'bg-amber-soft text-amber');
INSERT INTO categories (slug, name, icon, color) VALUES ('management-business', 'Management & Business', 'brief', 'bg-purple-soft text-purple');
INSERT INTO categories (slug, name, icon, color) VALUES ('arts-humanities', 'Arts & Humanities', 'palette', 'bg-amber-soft text-amber');
INSERT INTO categories (slug, name, icon, color) VALUES ('law', 'Law', 'scale', 'bg-blue-soft text-blue');
INSERT INTO categories (slug, name, icon, color) VALUES ('design-creative', 'Design & Creative', 'palette', 'bg-pink-soft text-pink');
INSERT INTO categories (slug, name, icon, color) VALUES ('it-software', 'IT & Software', 'code', 'bg-blue-soft text-blue');
INSERT INTO categories (slug, name, icon, color) VALUES ('government-civil-services', 'Government & Civil Services', 'bank', 'bg-slate-soft text-slate');
INSERT INTO categories (slug, name, icon, color) VALUES ('defence', 'Defence', 'shield', 'bg-green-soft text-green');
INSERT INTO categories (slug, name, icon, color) VALUES ('banking-insurance', 'Banking & Insurance', 'bank', 'bg-amber-soft text-amber');
INSERT INTO categories (slug, name, icon, color) VALUES ('education-teaching', 'Education & Teaching', 'teach', 'bg-green-soft text-green');
INSERT INTO categories (slug, name, icon, color) VALUES ('agriculture', 'Agriculture', 'leaf', 'bg-green-soft text-green');
INSERT INTO categories (slug, name, icon, color) VALUES ('hospitality-tourism', 'Hospitality & Tourism', 'plane', 'bg-blue-soft text-blue');
INSERT INTO categories (slug, name, icon, color) VALUES ('media-communication', 'Media & Communication', 'mega', 'bg-red-soft text-red');
INSERT INTO categories (slug, name, icon, color) VALUES ('skilled-trades', 'Skilled Trades', 'wrench', 'bg-slate-soft text-slate');
INSERT INTO categories (slug, name, icon, color) VALUES ('sports-fitness', 'Sports & Fitness', 'trophy', 'bg-green-soft text-green');
INSERT INTO categories (slug, name, icon, color) VALUES ('entrepreneurship', 'Entrepreneurship', 'rocket', 'bg-amber-soft text-amber');
INSERT INTO categories (slug, name, icon, color) VALUES ('emerging-careers', 'Emerging Careers', 'bulb', 'bg-purple-soft text-purple');
