-- Adds every degree from the uploaded "CareerGuide -- Degree Master List"
-- PDF that isn't already one of the 10 rows V44 added (b-tech, diploma,
-- b-ed, mba, mca, b-sc, b-com, bba, phd, certificate) -- 124 new rows
-- across the PDF's ~20 category groupings (Engineering & Technology,
-- Computer Science & IT, Science, Commerce & Finance, Arts & Humanities,
-- Economics, Law, Medicine & Healthcare, Pharmacy, Nursing, Allied
-- Healthcare, Education, Architecture & Planning, Design & Fine Arts,
-- Media & Communication, Agriculture, Hospitality & Tourism, Sports).
--
-- The PDF's own "Modeling Note" page confirms this catalog's existing
-- shape is the intended one: Degree is meant to be an independent entity
-- that connects directly to a Discipline/Career (its own example shows one
-- degree, BTech, covering multiple disciplines) rather than being nested
-- under Specialization or Job Role -- exactly what V44/V51's
-- degrees/career_degrees tables already do. This migration is data-only:
-- it adds the missing Degree catalog rows themselves, matching V44's
-- original scope, but does NOT link any of them into career_degrees --
-- that's a deliberate separate step, same as how V47 (single-degree
-- linking) followed V44 (degree catalog) by three migrations, and V51
-- (many-to-many linking) is itself a separate migration from V44.
--
-- Naming/slug notes: a handful of PDF abbreviations collide with plain
-- English words if used as a bare slug ("me", "be", "march", "med"), so
-- those become b-eng/m-eng/m-arch/m-ed instead (titles still show the
-- PDF's own short form, e.g. "BE", "ME"). "Master of Surgery (MS)" is
-- slugged ms-surgery rather than the very generic "ms". Every other slug
-- is the PDF's own abbreviation, lowercased, hyphenating only where the
-- source already writes it as "B.X"/"M.X" (matching V44's b-tech/b-sc/
-- b-com/b-ed convention) rather than a run-together acronym like MBA/MBBS.
--
-- Descriptions and preparation_strategy text are newly written for this
-- migration (the PDF itself is only a title list, one page per category,
-- plus the modeling note above) -- each aims to be genuinely informative
-- rather than filler, but at this volume (124 rows) they're necessarily
-- more concise than V44's original 10 hand-crafted entries; several
-- closely-related variants (e.g. the five B.Sc/M.Sc CS&IT majors, or the
-- five AYUSH medicine degrees) intentionally share a similar structure
-- since the underlying degrees themselves are structurally similar (same
-- duration, same entrance-exam route, differing only in subject focus).
--
-- degree_exams/degree_skills/degree_resources (V44) are deliberately left
-- empty for all 124 -- populating real, specific entrance-exam/skill/
-- resource relations for each would need the same kind of grounded,
-- verifiable research V44's original 10 had, which this migration doesn't
-- have a source for; better empty than guessed.

INSERT INTO degrees (slug, title, description, icon, preparation_strategy) VALUES
    ('b-eng', 'BE', 'A 4-year undergraduate engineering degree (Bachelor of Engineering) -- functionally equivalent to a B.Tech and used interchangeably with it by many Indian universities, entered after 12th with Physics, Chemistry and Maths.', 'cap', 'Preparation is identical to B.Tech''s -- a strong NCERT-level Physics/Chemistry/Maths foundation through Class 11-12, followed by JEE-style previous-year papers and mock tests in the final stretch.'),
    ('m-eng', 'ME', 'A 2-year postgraduate engineering degree (Master of Engineering) -- functionally equivalent to an M.Tech, entered after a B.E./B.Tech, usually via GATE.', 'cap', 'GATE preparation centers on the specific engineering discipline''s core subjects, built on a solid undergraduate foundation; most aspirants prepare for 6-12 months with previous-year papers and topic-wise mocks.'),
    ('m-tech', 'M.Tech', 'A 2-year postgraduate engineering degree (Master of Technology), entered after a B.Tech/B.E. via GATE, deepening specialization in a specific engineering discipline ahead of research or senior technical roles.', 'cap', 'GATE preparation centers on the specific engineering discipline''s core subjects, built on a solid undergraduate foundation; most aspirants prepare for 6-12 months with previous-year papers and topic-wise mocks.'),
    ('phd-engineering', 'PhD in Engineering', 'A research doctorate in an engineering discipline, typically 3-5 years, for candidates aiming at university faculty roles or senior R&D positions in industry or research labs.', 'flask', 'Eligibility usually requires clearing GATE (for a funded ME/MTech en route) or a university-specific research entrance test after a master''s degree, plus identifying a research area and prospective guide.'),
    ('bca', 'BCA', 'A 3-year undergraduate computing degree (Bachelor of Computer Applications), entered after 12th in any stream -- a software-focused alternative to B.Tech CSE with a lighter core-engineering course load.', 'code', 'Most BCA admissions are 12th-marks-based or via a university-specific/CUET entrance test covering logical reasoning, basic maths and computer aptitude; prior exposure to programming fundamentals helps considerably.'),
    ('bsc-computer-science', 'B.Sc (Computer Science)', 'A 3-year undergraduate science degree majoring in Computer Science, covering programming, data structures and computing theory as an alternative entry point to B.Tech CSE.', 'code', NULL),
    ('msc-computer-science', 'M.Sc (Computer Science)', 'A 2-year postgraduate degree deepening Computer Science theory and systems knowledge, usually entered after a B.Sc/BCA in a computing-related field.', 'code', NULL),
    ('bsc-information-technology', 'B.Sc (Information Technology)', 'A 3-year undergraduate science degree majoring in Information Technology, focused on applied computing, networks and systems administration.', 'monitor', NULL),
    ('msc-information-technology', 'M.Sc (Information Technology)', 'A 2-year postgraduate degree deepening IT systems, networking and enterprise-technology knowledge, usually entered after a B.Sc IT/Computer Science or BCA.', 'monitor', NULL),
    ('bsc-data-science', 'B.Sc (Data Science)', 'A 3-year undergraduate degree focused on statistics, machine learning and data analysis -- a direct entry route into data analyst and data scientist roles.', 'chart', NULL),
    ('msc-data-science', 'M.Sc (Data Science)', 'A 2-year postgraduate degree deepening statistical modelling, machine learning and large-scale data engineering, usually entered after a B.Sc in Data Science, Statistics or Computer Science.', 'chart', NULL),
    ('bsc-artificial-intelligence', 'B.Sc (Artificial Intelligence)', 'A 3-year undergraduate degree focused on machine learning, neural networks and AI systems -- a direct entry route into AI/ML engineering roles.', 'chip', NULL),
    ('msc-artificial-intelligence', 'M.Sc (Artificial Intelligence)', 'A 2-year postgraduate degree deepening machine learning theory and applied AI systems, usually entered after a B.Sc in AI, Computer Science or a related field.', 'chip', NULL),
    ('bsc-cybersecurity', 'B.Sc (Cybersecurity)', 'A 3-year undergraduate degree focused on network security, ethical hacking and information-security fundamentals -- a direct entry route into cybersecurity analyst roles.', 'shield', NULL),
    ('msc-cybersecurity', 'M.Sc (Cybersecurity)', 'A 2-year postgraduate degree deepening security architecture, threat analysis and applied cryptography, usually entered after a B.Sc in Cybersecurity, Computer Science or IT.', 'shield', NULL),
    ('phd-computer-science', 'PhD in Computer Science', 'A research doctorate in Computer Science, typically 3-5 years, for candidates aiming at university faculty roles or senior research positions in academia or industry labs.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET or GATE (for a funded ME/MTech route) plus a strong master''s-level record, alongside identifying a research area and prospective guide.'),
    ('phd-information-technology', 'PhD in Information Technology', 'A research doctorate in Information Technology, typically 3-5 years, for candidates aiming at university faculty roles or senior research and architecture positions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET or GATE plus a strong master''s-level record, alongside identifying a research area and prospective guide.'),
    ('msc', 'M.Sc', 'A 2-year postgraduate science degree, usually in Physics, Chemistry, Biology, Mathematics or a related discipline, entered after a B.Sc and a common step toward research, teaching or a PhD.', 'flask', 'Admission is largely through university-specific or CUET-PG entrance tests covering the chosen subject area; a strong B.Sc academic record matters more than any single entrance exam here.'),
    ('m-com', 'M.Com', 'A 2-year postgraduate commerce degree deepening accounting, finance, taxation and business-law knowledge, usually entered after a B.Com and a common step toward CA/CS/CMA or teaching.', 'chart', 'Most M.Com admissions are B.Com-marks-based or via a university-specific/CUET-PG entrance test covering accounting, economics and general aptitude.'),
    ('bms', 'BMS', 'A 3-year undergraduate management degree (Bachelor of Management Studies) with a broader, more integrated management curriculum than a standard BBA, covering finance, marketing, HR and operations together from year one.', 'brief', NULL),
    ('mms', 'MMS', 'A 2-year postgraduate management degree (Master of Management Studies), largely equivalent to an MBA and common at Indian university-affiliated management institutes, entered after a bachelor''s degree via CET/CAT-style exams.', 'brief', NULL),
    ('bbm', 'BBM', 'A 3-year undergraduate business degree (Bachelor of Business Management), similar in scope to a BBA, covering management fundamentals across marketing, HR, finance and operations.', 'brief', NULL),
    ('pgdm', 'PGDM', 'A 2-year postgraduate management diploma offered by autonomous business schools (not university-affiliated), equivalent in standing to an MBA and often more industry-curriculum-flexible, entered via CAT/XAT/similar exams.', 'brief', 'Preparation mirrors MBA/CAT prep -- Verbal Ability & Reading Comprehension, Data Interpretation & Logical Reasoning and Quantitative Ability -- followed by group discussions and interviews at the shortlisting stage.'),
    ('phd-management', 'PhD in Management', 'A research doctorate in management (often called a Fellow Programme, FPM, at some institutes), typically 3-5 years, for candidates aiming at business-school faculty roles or senior corporate strategy/research positions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET, CAT/GMAT or an institute''s own research-aptitude test after a master''s degree, plus identifying a research area and prospective guide.'),
    ('ba', 'B.A.', 'A 3-year undergraduate arts degree spanning humanities and social-science subjects (History, Political Science, English, Sociology, Psychology and more), a broad and common entry point into teaching, civil services, media, law and research paths.', 'book', 'Admission is largely 12th-marks-based or through CUET at central and many state universities; preparation centers on scoring well in board exams plus CUET''s general test and the chosen subject paper.'),
    ('ma', 'M.A.', 'A 2-year postgraduate arts degree deepening a chosen humanities or social-science subject, usually entered after a B.A. and a common step toward UGC-NET/teaching, research or a PhD.', 'book', 'Admission is largely through university-specific or CUET-PG entrance tests in the chosen subject; a strong B.A. academic record matters more than any single entrance exam here.'),
    ('phd-arts-humanities', 'PhD in Arts & Humanities', 'A research doctorate in a humanities subject, typically 3-5 years, for candidates aiming at university faculty roles or senior research positions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET (JRF for a funded position) after a master''s degree, plus identifying a research area and prospective guide.'),
    ('ba-economics', 'B.A. (Economics)', 'A 3-year undergraduate arts degree majoring in Economics -- theory, statistics and policy -- the traditional entry route into economic research, policy and analyst roles.', 'chart', NULL),
    ('bsc-economics', 'B.Sc (Economics)', 'A 3-year undergraduate science degree majoring in Economics with a heavier quantitative/statistics load than the B.A. route, offered at a smaller set of universities.', 'chart', NULL),
    ('ma-economics', 'M.A. (Economics)', 'A 2-year postgraduate degree deepening economic theory, econometrics and policy analysis, usually entered after a B.A./B.Sc in Economics and a common step toward research, policy roles or a PhD.', 'chart', NULL),
    ('msc-economics', 'M.Sc (Economics)', 'A 2-year postgraduate degree with a more quantitative/econometrics-heavy curriculum than the M.A. route, usually entered after a B.A./B.Sc in Economics or a related quantitative field.', 'chart', NULL),
    ('phd-economics', 'PhD in Economics', 'A research doctorate in Economics, typically 3-5 years, for candidates aiming at university faculty roles or senior positions in policy research, think tanks or multilateral institutions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET or a university-specific research entrance test after a master''s degree, plus identifying a research area and prospective guide.'),
    ('llb', 'LLB', 'A 3-year professional law degree entered after any bachelor''s degree -- the traditional route into litigation, corporate law and the judiciary for graduates who didn''t pursue an integrated 5-year law degree.', 'scale', 'Most LLB admissions are through university-specific entrance tests or CUET-LLB, covering legal aptitude, general knowledge, English and reasoning.'),
    ('ba-llb', 'BA LLB', 'A 5-year integrated undergraduate law degree combining a B.A. with an LLB, entered directly after 12th -- the most common route into India''s National Law Universities.', 'scale', 'Admission at most National Law Universities is through CLAT, testing English, legal reasoning, logical reasoning, quantitative techniques and general knowledge; some private universities also accept LSAT-India.'),
    ('bba-llb', 'BBA LLB', 'A 5-year integrated undergraduate law degree combining a BBA with an LLB, entered directly after 12th -- suited to students aiming at corporate law, M&A or business-law careers.', 'scale', 'Admission follows the same route as BA LLB -- primarily CLAT, with some private universities also accepting LSAT-India.'),
    ('bcom-llb', 'BCom LLB', 'A 5-year integrated undergraduate law degree combining a B.Com with an LLB, entered directly after 12th -- suited to students aiming at tax law, corporate law or company-secretary-adjacent careers.', 'scale', 'Admission follows the same route as BA LLB -- primarily CLAT, with some private universities also accepting LSAT-India.'),
    ('bsc-llb', 'BSc LLB', 'A 5-year integrated undergraduate law degree combining a B.Sc with an LLB, entered directly after 12th -- a less common but growing combination for students aiming at intellectual-property or technology law.', 'scale', 'Admission follows the same route as BA LLB -- primarily CLAT, with some private universities also accepting LSAT-India.'),
    ('llm', 'LLM', 'A 1-2 year postgraduate law degree deepening a specialized area of law (constitutional, corporate, IP, criminal and more), entered after an LLB and a common step toward academia, specialized practice or the judiciary.', 'scale', 'Most LLM admissions are through CLAT-PG or university-specific entrance tests covering the core areas of law from the LLB curriculum.'),
    ('phd-law', 'PhD in Law', 'A research doctorate in Law, typically 3-5 years, for candidates aiming at law-school faculty roles or senior legal-research positions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET or a university-specific research entrance test after an LLM, plus identifying a research area and prospective guide.'),
    ('mbbs', 'MBBS', 'A 5.5-year undergraduate medical degree (Bachelor of Medicine, Bachelor of Surgery), including a compulsory 1-year rotating internship -- the foundational qualification to practice allopathic medicine in India.', 'steth', 'NEET-UG is the sole entrance exam for MBBS admission nationwide; preparation typically runs 1-2 years covering NCERT Physics, Chemistry and Biology in depth, with extensive previous-year-paper and mock-test practice.'),
    ('bds', 'BDS', 'A 5-year undergraduate dental degree (Bachelor of Dental Surgery), including a compulsory 1-year internship -- the foundational qualification to practice dentistry in India.', 'steth', 'Admission is through NEET-UG, the same entrance exam used for MBBS, with dental seats allotted through the same counselling process.'),
    ('bams', 'BAMS', 'A 5.5-year undergraduate degree in Ayurvedic medicine (Bachelor of Ayurvedic Medicine and Surgery), including a compulsory internship, for practicing traditional Ayurvedic medicine alongside modern diagnostic methods.', 'leaf', 'Admission is through NEET-UG, with BAMS seats allotted through the AYUSH counselling process.'),
    ('bhms', 'BHMS', 'A 5.5-year undergraduate degree in homeopathic medicine (Bachelor of Homeopathic Medicine and Surgery), including a compulsory internship, for practicing homeopathic treatment.', 'leaf', 'Admission is through NEET-UG, with BHMS seats allotted through the AYUSH counselling process.'),
    ('bums', 'BUMS', 'A 5.5-year undergraduate degree in Unani medicine (Bachelor of Unani Medicine and Surgery), including a compulsory internship, for practicing Unani traditional medicine.', 'leaf', 'Admission is through NEET-UG, with BUMS seats allotted through the AYUSH counselling process.'),
    ('bsms', 'BSMS', 'A 5.5-year undergraduate degree in Siddha medicine (Bachelor of Siddha Medicine and Surgery), including a compulsory internship, for practicing the traditional Siddha system of medicine common in South India.', 'leaf', 'Admission is through NEET-UG, with BSMS seats allotted through the AYUSH counselling process.'),
    ('bnys', 'BNYS', 'A 5.5-year undergraduate degree (Bachelor of Naturopathy and Yogic Sciences), including a compulsory internship, combining naturopathy, yoga therapy and modern preventive-health principles.', 'leaf', 'Admission is through NEET-UG, with BNYS seats allotted through the AYUSH counselling process.'),
    ('md', 'MD', 'A 3-year postgraduate medical degree (Doctor of Medicine) specializing in a non-surgical branch (Medicine, Pediatrics, Dermatology and more), entered after MBBS -- the standard route into specialist physician roles.', 'steth', 'Admission is through NEET-PG, testing the full MBBS curriculum; residency/seat allocation follows a centralized and state-level counselling process.'),
    ('ms-surgery', 'MS', 'A 3-year postgraduate medical degree (Master of Surgery) specializing in a surgical branch (General Surgery, Orthopedics, ENT and more), entered after MBBS -- the standard route into specialist surgeon roles.', 'steth', 'Admission is through NEET-PG, testing the full MBBS curriculum; residency/seat allocation follows a centralized and state-level counselling process.'),
    ('mds', 'MDS', 'A 3-year postgraduate dental degree (Master of Dental Surgery) specializing in a dental branch (Orthodontics, Oral Surgery and more), entered after BDS.', 'steth', 'Admission is through NEET-MDS, testing the full BDS curriculum.'),
    ('dm', 'DM', 'A 3-year super-specialty medical degree (Doctorate of Medicine) in a narrow field (Cardiology, Neurology, Nephrology and more), entered after an MD -- the highest clinical qualification in that specialty.', 'steth', 'Admission is through NEET-SS, open to MD/MS holders in the relevant parent specialty.'),
    ('mch', 'MCh', 'A 3-year super-specialty surgical degree (Master of Chirurgiae) in a narrow surgical field (Neurosurgery, Cardiothoracic Surgery, Urology and more), entered after an MS -- the highest surgical qualification in that specialty.', 'steth', 'Admission is through NEET-SS, open to MS holders in the relevant parent surgical specialty.'),
    ('dpharm', 'D.Pharm', 'A 2-year diploma in pharmacy, entered after 12th with Science -- the minimum qualification to register as a pharmacist and run a retail pharmacy in India.', 'flask', 'Admission is largely 12th-marks-based or via state-level diploma entrance tests, with a strong Class 11-12 Chemistry and Biology/Maths foundation.'),
    ('bpharm', 'B.Pharm', 'A 4-year undergraduate pharmacy degree, entered after 12th with Science, covering pharmacology, pharmaceutical chemistry and drug formulation -- the standard route into pharmacist, quality-control and pharma-industry roles.', 'flask', 'Most B.Pharm admissions are 12th-marks-based or through state-level/university entrance tests such as GPAT-eligible programs'' own tests, with a strong Physics, Chemistry and Biology/Maths foundation.'),
    ('pharmd', 'Pharm.D', 'A 6-year integrated doctoral pharmacy degree (5 years coursework + 1 year internship, or 3 years after B.Pharm) focused on clinical pharmacy practice and direct patient care alongside physicians.', 'flask', 'Admission is 12th-marks-based or via state-level/university entrance tests similar to B.Pharm; a Pharm.D (Post-Baccalaureate) track is also open to existing B.Pharm graduates via GPAT.'),
    ('mpharm', 'M.Pharm', 'A 2-year postgraduate pharmacy degree specializing in a branch (Pharmaceutics, Pharmacology, Pharmaceutical Chemistry and more), entered after a B.Pharm via GPAT.', 'flask', 'GPAT preparation covers the full B.Pharm syllabus with an emphasis on pharmaceutical chemistry, pharmacology and pharmaceutics; most aspirants prepare for 6-12 months.'),
    ('phd-pharmaceutical-sciences', 'PhD in Pharmaceutical Sciences', 'A research doctorate in pharmaceutical sciences, typically 3-5 years, for candidates aiming at university faculty roles or senior R&D positions in the pharmaceutical industry.', 'flask', 'Eligibility usually requires clearing GPAT/UGC-NET or a university-specific research entrance test after an M.Pharm, plus identifying a research area and prospective guide.'),
    ('anm', 'ANM', 'A 2-year diploma (Auxiliary Nurse Midwifery), entered after 12th -- the entry-level qualification for community-health and midwifery support roles, mainly in rural and public-health settings.', 'heart', 'Admission is largely 12th-marks-based or via state-level entrance tests; no separate national entrance exam is required.'),
    ('gnm', 'GNM', 'A 3.5-year diploma (General Nursing and Midwifery), entered after 12th with Science -- a widely-held qualification to register and practice as a nurse in India, alongside the BSc Nursing route.', 'heart', 'Admission is largely 12th-marks-based or via state-level/institutional entrance tests, with a Science background (Biology) generally preferred.'),
    ('bsc-nursing', 'B.Sc Nursing', 'A 4-year undergraduate nursing degree, entered after 12th with Science (Biology), combining nursing practice with a broader academic foundation than the GNM diploma route.', 'heart', 'Admission is through NEET-UG at many institutions, or state-level/university-specific entrance tests, with a strong Class 11-12 Biology and Chemistry foundation.'),
    ('post-basic-bsc-nursing', 'Post Basic B.Sc Nursing', 'A 2-year degree for registered GNM-qualified nurses to upgrade to a B.Sc Nursing qualification while continuing to practice.', 'heart', 'Admission is open to GNM diploma holders registered with a State Nursing Council, usually via state-level or institutional entrance tests.'),
    ('msc-nursing', 'M.Sc Nursing', 'A 2-year postgraduate nursing degree specializing in a clinical or teaching-focused branch (Medical-Surgical, Pediatric, Psychiatric Nursing and more), entered after a B.Sc Nursing.', 'heart', 'Admission is through state-level or institutional entrance tests covering the B.Sc Nursing curriculum, alongside registered nursing experience requirements at some institutes.'),
    ('phd-nursing', 'PhD in Nursing', 'A research doctorate in Nursing, typically 3-5 years, for candidates aiming at nursing-college faculty roles or senior clinical-research/administrative positions.', 'flask', 'Eligibility usually requires clearing UGC-NET or a university-specific research entrance test after an M.Sc Nursing, plus identifying a research area and prospective guide.'),
    ('bpt', 'BPT', 'A 4.5-year undergraduate degree (Bachelor of Physiotherapy), including a compulsory internship, entered after 12th with Science -- the standard qualification to practice as a physiotherapist.', 'pulse', 'Admission is largely 12th-marks-based or via state-level/institutional entrance tests, with a strong Biology, Physics and Chemistry foundation.'),
    ('mpt', 'MPT', 'A 2-year postgraduate physiotherapy degree specializing in a branch (Orthopedics, Neurology, Sports and more), entered after a BPT.', 'pulse', 'Admission is through state-level or institutional entrance tests covering the BPT curriculum.'),
    ('bot', 'BOT', 'A 4-year undergraduate degree (Bachelor of Occupational Therapy), including internship, entered after 12th with Science -- trains therapists to help patients regain everyday living and work skills after injury or illness.', 'pulse', 'Admission is largely 12th-marks-based or via state-level/institutional entrance tests, with a Biology background generally preferred.'),
    ('mot', 'MOT', 'A 2-year postgraduate occupational-therapy degree specializing in a clinical branch, entered after a BOT.', 'pulse', 'Admission is through state-level or institutional entrance tests covering the BOT curriculum.'),
    ('boptom', 'BOptom', 'A 4-year undergraduate degree (Bachelor of Optometry), entered after 12th with Science, covering eye examination, vision correction and optical-device fitting -- the standard qualification to practice as an optometrist.', 'pulse', 'Admission is largely 12th-marks-based or via state-level/institutional entrance tests, with a Physics, Chemistry and Biology/Maths foundation.'),
    ('moptom', 'MOptom', 'A 2-year postgraduate optometry degree specializing in a clinical branch (Contact Lens, Low Vision, Ocular Disease and more), entered after a BOptom.', 'pulse', 'Admission is through state-level or institutional entrance tests covering the BOptom curriculum.'),
    ('baslp', 'BASLP', 'A 4-year undergraduate degree (Bachelor of Audiology and Speech-Language Pathology), including internship, entered after 12th with Science -- trains professionals to diagnose and treat hearing and speech/language disorders.', 'pulse', 'Admission is largely 12th-marks-based or via state-level/institutional entrance tests, with a Biology background generally preferred.'),
    ('maslp', 'MASLP', 'A 2-year postgraduate degree in audiology and speech-language pathology, specializing in a clinical branch, entered after a BASLP.', 'pulse', 'Admission is through state-level or institutional entrance tests covering the BASLP curriculum.'),
    ('m-ed', 'M.Ed', 'A 2-year postgraduate education degree deepening pedagogy, educational psychology and research methods, usually entered after a B.Ed and a common step toward teacher-education faculty roles or school leadership.', 'teach', 'Admission is usually through a state or university-level M.Ed entrance test, or CUET-PG at many universities, testing teaching aptitude and the graduate''s B.Ed academic record.'),
    ('b-el-ed', 'B.El.Ed', 'A 4-year integrated undergraduate degree (Bachelor of Elementary Education) combining a general degree with elementary-teacher training, entered directly after 12th -- a direct route into primary-school teaching without a separate B.Ed.', 'teach', 'Admission is usually through a university-specific entrance test (notably Delhi University''s), testing general aptitude, language and teaching aptitude.'),
    ('d-el-ed', 'D.El.Ed', 'A 2-year diploma (Diploma in Elementary Education), entered after 12th -- the standard qualification to teach at the primary-school level in most Indian states, often via distance/open-learning routes too.', 'teach', 'Admission is largely 12th-marks-based or via state-level entrance tests; no national-level entrance exam is required.'),
    ('ba-bed', 'BA BEd', 'A 4-year integrated undergraduate degree combining a B.A. with a B.Ed, entered directly after 12th -- a direct route into secondary-school teaching in humanities subjects without a separate B.Ed afterward.', 'teach', 'Admission is usually through a state or university-level integrated-B.Ed entrance test, or CUET at many universities.'),
    ('bsc-bed', 'BSc BEd', 'A 4-year integrated undergraduate degree combining a B.Sc with a B.Ed, entered directly after 12th -- a direct route into secondary-school teaching in science subjects without a separate B.Ed afterward.', 'teach', 'Admission is usually through a state or university-level integrated-B.Ed entrance test, or CUET at many universities.'),
    ('phd-education', 'PhD in Education', 'A research doctorate in Education, typically 3-5 years, for candidates aiming at teacher-education faculty roles or senior educational-policy/research positions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET or a university-specific research entrance test after an M.Ed, plus identifying a research area and prospective guide.'),
    ('b-arch', 'B.Arch', 'A 5-year undergraduate degree (Bachelor of Architecture), entered after 12th -- the foundational, professionally-recognized qualification to practice as an architect in India.', 'bld', 'Admission is through NATA or JEE (Paper 2), testing drawing, aesthetic sensitivity, mathematics and architectural aptitude; most aspirants combine board-exam prep with dedicated drawing and aptitude practice.'),
    ('m-arch', 'M.Arch', 'A 2-year postgraduate degree specializing in a branch of architecture (Urban Design, Landscape, Sustainable Architecture and more), entered after a B.Arch.', 'bld', 'Admission is through GATE (Architecture & Planning) or university-specific entrance tests covering the B.Arch curriculum plus a portfolio review.'),
    ('b-plan', 'B.Plan', 'A 4-year undergraduate degree (Bachelor of Planning), entered after 12th, focused on urban and regional planning -- land use, transportation and infrastructure planning -- distinct from architecture''s building-design focus.', 'bld', 'Admission is through NATA/JEE-style planning-aptitude tests or university-specific entrance exams at planning schools such as SPAs.'),
    ('m-plan', 'M.Plan', 'A 2-year postgraduate degree specializing in a branch of urban/regional planning, entered after a B.Plan, B.Arch or a related undergraduate degree.', 'bld', 'Admission is through GATE (Architecture & Planning) or university-specific entrance tests.'),
    ('phd-architecture', 'PhD in Architecture', 'A research doctorate in Architecture, typically 3-5 years, for candidates aiming at architecture-school faculty roles or senior research positions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET or GATE plus a strong M.Arch academic record, alongside identifying a research area and prospective guide.'),
    ('phd-urban-planning', 'PhD in Urban Planning', 'A research doctorate in Urban Planning, typically 3-5 years, for candidates aiming at planning-school faculty roles or senior policy-research positions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET or GATE plus a strong M.Plan academic record, alongside identifying a research area and prospective guide.'),
    ('b-des', 'B.Des', 'A 4-year undergraduate design degree, entered after 12th, covering a chosen design discipline (Product, Communication, UX, Fashion and more) through studio-based, project-driven learning.', 'palette', 'Admission is through NID DAT, UCEED, CEED or institute-specific design-aptitude tests, testing visual/spatial reasoning, sketching and design thinking rather than rote academic knowledge.'),
    ('m-des', 'M.Des', 'A 2-year postgraduate design degree specializing in a chosen discipline, entered after a B.Des or a related bachelor''s degree, often via UCEED/CEED.', 'palette', 'Admission is through CEED or institute-specific entrance tests plus a portfolio review and studio test.'),
    ('bfa', 'BFA', 'A 4-year undergraduate degree (Bachelor of Fine Arts), entered after 12th, covering a chosen fine-art discipline (Painting, Sculpture, Applied Art and more) through studio practice.', 'palette', 'Admission is through a portfolio submission and/or institute-specific practical drawing/aptitude test.'),
    ('mfa', 'MFA', 'A 2-year postgraduate fine-arts degree specializing in a chosen discipline, entered after a BFA.', 'palette', 'Admission is through a portfolio submission and institute-specific practical test or interview.'),
    ('phd-design', 'PhD in Design', 'A research doctorate in Design, typically 3-5 years, for candidates aiming at design-school faculty roles or senior design-research positions.', 'flask', 'Eligibility usually requires clearing UGC-NET or a university-specific research entrance test after an M.Des, plus identifying a research area and prospective guide.'),
    ('phd-fine-arts', 'PhD in Fine Arts', 'A research doctorate in Fine Arts, typically 3-5 years, for candidates aiming at art-school faculty roles or senior research/curatorial positions.', 'flask', 'Eligibility usually requires clearing UGC-NET or a university-specific research entrance test after an MFA, plus a portfolio and identifying a research area.'),
    ('bjmc', 'BJMC', 'A 3-year undergraduate degree (Bachelor of Journalism and Mass Communication), entered after 12th, covering reporting, editing, broadcast and digital media across print, TV and online.', 'mega', 'Admission is largely 12th-marks-based or via university-specific/CUET entrance tests covering general knowledge, current affairs, English and media aptitude.'),
    ('bmm', 'BMM', 'A 3-year undergraduate degree (Bachelor of Mass Media), entered after 12th, with a broader media-industry curriculum spanning journalism, advertising, PR and film alongside core mass-communication theory.', 'mega', 'Admission is largely 12th-marks-based or via university-specific entrance tests covering general knowledge, English and media aptitude.'),
    ('ba-journalism', 'B.A. in Journalism', 'A 3-year undergraduate arts degree majoring in Journalism within a broader humanities curriculum, entered after 12th.', 'mega', NULL),
    ('ba-mass-communication', 'B.A. in Mass Communication', 'A 3-year undergraduate arts degree majoring in Mass Communication within a broader humanities curriculum, entered after 12th.', 'mega', NULL),
    ('m-journalism', 'Master of Journalism', 'A 2-year postgraduate degree deepening reporting, editing and media-ethics skills, usually entered after a bachelor''s degree in journalism, mass communication or any discipline with a strong writing aptitude.', 'mega', 'Admission is largely through university-specific entrance tests covering general knowledge, current affairs, English and media aptitude.'),
    ('m-mass-communication', 'Master of Mass Communication', 'A 2-year postgraduate degree deepening media theory, production and strategic communication skills, usually entered after a bachelor''s degree in mass communication or a related field.', 'mega', 'Admission is largely through university-specific entrance tests covering general knowledge, current affairs, English and media aptitude.'),
    ('ma-journalism', 'M.A. in Journalism', 'A 2-year postgraduate arts degree majoring in Journalism within a broader humanities framework, usually entered after a B.A.', 'mega', NULL),
    ('ma-mass-communication', 'M.A. in Mass Communication', 'A 2-year postgraduate arts degree majoring in Mass Communication within a broader humanities framework, usually entered after a B.A.', 'mega', NULL),
    ('phd-mass-communication', 'PhD in Mass Communication', 'A research doctorate in Mass Communication, typically 3-5 years, for candidates aiming at journalism-school faculty roles or senior media-research positions.', 'flask', 'Eligibility usually requires clearing UGC-NET/CSIR-NET or a university-specific research entrance test after a master''s degree, plus identifying a research area and prospective guide.'),
    ('bsc-agriculture', 'B.Sc Agriculture', 'A 4-year undergraduate degree, entered after 12th with Science, covering crop science, soil science and farm management -- the standard route into agronomy, agri-extension and agribusiness roles.', 'leaf', 'Admission is through ICAR AIEEA or state-level/university entrance tests, with a strong Physics, Chemistry and Biology/Maths foundation.'),
    ('bsc-horticulture', 'B.Sc Horticulture', 'A 4-year undergraduate degree, entered after 12th with Science, focused on fruit, vegetable and ornamental-plant cultivation.', 'leaf', 'Admission is through ICAR AIEEA or state-level/university entrance tests, with a Science background.'),
    ('bsc-forestry', 'B.Sc Forestry', 'A 4-year undergraduate degree, entered after 12th with Science, covering forest management, conservation and wildlife-adjacent ecology -- the standard route into forestry-service and conservation roles.', 'leaf', 'Admission is through ICAR AIEEA or state-level/university entrance tests, with a Science background.'),
    ('bfsc', 'BFSc', 'A 4-year undergraduate degree (Bachelor of Fisheries Science), entered after 12th with Science, covering aquaculture, fish biology and fisheries management.', 'leaf', 'Admission is through ICAR AIEEA or state-level/university entrance tests, with a Science background.'),
    ('bvsc-ah', 'BVSc & AH', 'A 5.5-year undergraduate degree (Bachelor of Veterinary Science and Animal Husbandry), including a compulsory internship, entered after 12th with Science -- the foundational qualification to practice as a veterinarian in India.', 'leaf', 'Admission is through NEET-UG, with BVSc & AH seats allotted through a centralized veterinary counselling process.'),
    ('msc-agriculture', 'M.Sc Agriculture', 'A 2-year postgraduate degree specializing in a branch of agricultural science (Agronomy, Soil Science, Plant Breeding and more), entered after a B.Sc Agriculture.', 'leaf', 'Admission is through ICAR AIEEA-PG or state-level/university entrance tests covering the B.Sc Agriculture curriculum.'),
    ('msc-horticulture', 'M.Sc Horticulture', 'A 2-year postgraduate degree specializing in a branch of horticultural science, entered after a B.Sc Horticulture or Agriculture.', 'leaf', 'Admission is through ICAR AIEEA-PG or state-level/university entrance tests.'),
    ('msc-forestry', 'M.Sc Forestry', 'A 2-year postgraduate degree specializing in a branch of forestry science, entered after a B.Sc Forestry.', 'leaf', 'Admission is through ICAR AIEEA-PG or state-level/university entrance tests.'),
    ('mvsc', 'MVSc', 'A 2-3 year postgraduate veterinary degree (Master of Veterinary Science) specializing in a clinical or research branch, entered after a BVSc & AH.', 'leaf', 'Admission is through ICAR AIEEA-PG or state-level/university entrance tests covering the BVSc curriculum.'),
    ('phd-agricultural-sciences', 'PhD in Agricultural Sciences', 'A research doctorate in an agricultural-science branch, typically 3-5 years, for candidates aiming at agricultural-university faculty roles or senior research positions at ICAR institutes.', 'flask', 'Eligibility usually requires clearing ICAR AIEEA-PG or a university-specific research entrance test after a master''s degree, plus identifying a research area and prospective guide.'),
    ('bhm', 'BHM', 'A 4-year undergraduate degree (Bachelor of Hotel Management), entered after 12th, covering front-office, food & beverage, housekeeping and hospitality operations.', 'building', 'Admission is through NCHM JEE (for NCHMCT-affiliated institutes) or university-specific/state entrance tests, testing numerical, reasoning, English and general-knowledge aptitude.'),
    ('bhmct', 'BHMCT', 'A 4-year undergraduate degree (Bachelor of Hotel Management and Catering Technology), broadly equivalent to a BHM with an added catering-technology and culinary-science focus.', 'building', 'Admission is through NCHM JEE or university-specific entrance tests, similar to BHM.'),
    ('bsc-hospitality-management', 'B.Sc Hospitality Management', 'A 3-year undergraduate science degree covering hotel and broader hospitality-sector operations and management, entered after 12th.', 'building', 'Admission is largely 12th-marks-based or via institute-specific entrance tests.'),
    ('bsc-hotel-management', 'B.Sc Hotel Management', 'A 3-year undergraduate science degree focused specifically on hotel operations and management, entered after 12th -- a lighter-weight alternative to the 4-year BHM.', 'building', 'Admission is largely 12th-marks-based or via institute-specific entrance tests.'),
    ('bttm', 'BTTM', 'A 3-year undergraduate degree (Bachelor of Tourism and Travel Management), entered after 12th, covering tour operations, travel-agency management and destination planning.', 'plane', 'Admission is largely 12th-marks-based or via university-specific entrance tests.'),
    ('ba-tourism', 'B.A. in Tourism', 'A 3-year undergraduate arts degree majoring in Tourism Studies within a broader humanities curriculum, entered after 12th.', 'plane', NULL),
    ('m-hotel-management', 'Master of Hotel Management', 'A 2-year postgraduate degree deepening strategic hospitality operations and management, usually entered after a BHM/BHMCT or a related bachelor''s degree.', 'building', 'Admission is through institute-specific entrance tests and, at many institutes, relevant work experience.'),
    ('mttm', 'MTTM', 'A 2-year postgraduate degree (Master of Tourism and Travel Management), entered after a bachelor''s degree, deepening tourism-industry strategy, destination management and travel-business operations.', 'plane', 'Admission is through university-specific entrance tests covering general aptitude and tourism-industry awareness.'),
    ('msc-hospitality-management', 'M.Sc Hospitality Management', 'A 2-year postgraduate science degree deepening hospitality-sector strategy and operations, usually entered after a B.Sc/BHM in hospitality or hotel management.', 'building', 'Admission is through institute-specific entrance tests.'),
    ('bped', 'BPEd', 'A 3-4 year undergraduate degree (Bachelor of Physical Education), entered after 12th, training candidates to teach physical education and coach school/college-level sports.', 'trophy', 'Admission is usually through a state or university-level physical-education entrance test, including a physical-fitness/skill assessment alongside a written test.'),
    ('bpes', 'BPES', 'A 3-year undergraduate degree (Bachelor of Physical Education and Sports), entered after 12th, combining physical-education pedagogy with a broader sports-science foundation.', 'trophy', 'Admission is usually through a state or university-level entrance test with a physical-fitness/skill assessment component.'),
    ('bsc-sports-science', 'B.Sc Sports Science', 'A 3-year undergraduate science degree covering exercise physiology, sports biomechanics and nutrition -- the standard route into sports-science, fitness-training and athlete-support roles.', 'trophy', 'Admission is largely 12th-marks-based or via institute-specific entrance tests, with a Science background generally preferred.'),
    ('bsc-sports-management', 'B.Sc Sports Management', 'A 3-year undergraduate science degree covering sports-event management, sports marketing and athletic administration.', 'trophy', 'Admission is largely 12th-marks-based or via institute-specific entrance tests.'),
    ('mped', 'MPEd', 'A 2-year postgraduate degree (Master of Physical Education), entered after a BPEd, deepening sports pedagogy, coaching science and sports psychology.', 'trophy', 'Admission is usually through a state or university-level entrance test covering the BPEd curriculum and physical-fitness assessment.'),
    ('msc-sports-science', 'M.Sc Sports Science', 'A 2-year postgraduate science degree specializing in a branch of sports science (Exercise Physiology, Sports Nutrition, Biomechanics and more), entered after a B.Sc Sports Science.', 'trophy', 'Admission is through institute-specific entrance tests covering the B.Sc Sports Science curriculum.'),
    ('msc-sports-management', 'M.Sc Sports Management', 'A 2-year postgraduate degree deepening sports-business strategy, event management and athletic administration, entered after a B.Sc Sports Management or a related bachelor''s degree.', 'trophy', 'Admission is through institute-specific entrance tests.'),
    ('phd-sports-science', 'PhD in Sports Science', 'A research doctorate in Sports Science, typically 3-5 years, for candidates aiming at sports-science faculty roles or senior research positions in athletic performance.', 'flask', 'Eligibility usually requires clearing UGC-NET or a university-specific research entrance test after an M.Sc Sports Science, plus identifying a research area and prospective guide.');
