INSERT INTO assessment_questions (id, question, sort_order) VALUES ('interest', 'Which of these sounds most exciting to spend your day on?', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (1, 'interest', 'a', 'Building, fixing or designing physical things', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (2, 'interest', 'b', 'Helping people feel better, physically or mentally', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (3, 'interest', 'c', 'Designing something people will see and use', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (4, 'interest', 'd', 'Telling stories or communicating ideas', 3);
INSERT INTO assessment_questions (id, question, sort_order) VALUES ('strength', 'Which of these is closest to your biggest strength?', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (5, 'strength', 'a', 'Analytical thinking & solving complex problems', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (6, 'strength', 'b', 'Leading, organizing and motivating a team', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (7, 'strength', 'c', 'Clear communication & persuasion', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (8, 'strength', 'd', 'Practical, hands-on problem solving', 3);
INSERT INTO assessment_questions (id, question, sort_order) VALUES ('academics', 'Which subjects do you enjoy or do best in?', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (9, 'academics', 'a', 'Physics, Chemistry & Mathematics', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (10, 'academics', 'b', 'Biology & Life Sciences', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (11, 'academics', 'c', 'Economics, Accounts & Business Studies', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (12, 'academics', 'd', 'History, Civics, Languages & the Arts', 3);
INSERT INTO assessment_questions (id, question, sort_order) VALUES ('skills', 'Which skill would you most like to get better at?', 3);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (13, 'skills', 'a', 'Coding & building software', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (14, 'skills', 'b', 'Visual design & creativity', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (15, 'skills', 'c', 'Working with numbers & financial models', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (16, 'skills', 'd', 'Working with your hands and real materials', 3);
INSERT INTO assessment_questions (id, question, sort_order) VALUES ('personality', 'How would your friends describe you?', 4);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (17, 'personality', 'a', 'Disciplined, structured and service-minded', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (18, 'personality', 'b', 'Independent, and comfortable with risk', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (19, 'personality', 'c', 'Patient, nurturing and a natural mentor', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (20, 'personality', 'd', 'Energetic, competitive and active', 3);
INSERT INTO assessment_questions (id, question, sort_order) VALUES ('goals', 'What matters most to you in a career?', 5);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (21, 'goals', 'a', 'Stability and serving the public', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (22, 'goals', 'b', 'Building something of my own', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (23, 'goals', 'c', 'Working at the cutting edge of technology', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (24, 'goals', 'd', 'Making a direct difference in people''s lives', 3);
INSERT INTO assessment_questions (id, question, sort_order) VALUES ('salary', 'How do you feel about salary vs. passion trade-offs right now?', 6);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (25, 'salary', 'a', 'I want the highest-paying path available', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (26, 'salary', 'b', 'I want steady, predictable income', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (27, 'salary', 'c', 'I''m fine with variable income for the right work', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (28, 'salary', 'd', 'I haven''t thought about it much yet', 3);
INSERT INTO assessment_questions (id, question, sort_order) VALUES ('workstyle', 'What kind of day-to-day work setting appeals to you?', 7);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (29, 'workstyle', 'a', 'Desk-based, tech-forward, flexible', 0);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (30, 'workstyle', 'b', 'People-facing, active, always moving', 1);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (31, 'workstyle', 'c', 'Outdoors or hands-on, tangible results', 2);
INSERT INTO assessment_options (id, question_id, option_key, label, sort_order) VALUES (32, 'workstyle', 'd', 'Structured corporate or institutional setting', 3);
SELECT setval(pg_get_serial_sequence('assessment_options','id'), 32);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (1, 'engineering-technology', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (1, 'skilled-trades', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (2, 'medical-healthcare', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (3, 'design-creative', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (3, 'media-communication', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (4, 'media-communication', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (4, 'arts-humanities', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (5, 'science-research', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (5, 'it-software', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (6, 'management-business', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (7, 'law', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (7, 'arts-humanities', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (8, 'skilled-trades', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (8, 'agriculture', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (9, 'engineering-technology', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (9, 'science-research', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (10, 'medical-healthcare', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (10, 'agriculture', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (11, 'commerce-finance', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (11, 'banking-insurance', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (12, 'arts-humanities', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (12, 'law', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (13, 'it-software', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (13, 'emerging-careers', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (14, 'design-creative', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (15, 'commerce-finance', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (15, 'banking-insurance', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (16, 'skilled-trades', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (16, 'agriculture', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (17, 'government-civil-services', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (17, 'defence', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (18, 'entrepreneurship', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (19, 'education-teaching', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (20, 'sports-fitness', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (20, 'hospitality-tourism', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (21, 'government-civil-services', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (21, 'banking-insurance', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (22, 'entrepreneurship', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (22, 'management-business', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (23, 'it-software', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (23, 'emerging-careers', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (24, 'medical-healthcare', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (24, 'education-teaching', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (25, 'it-software', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (25, 'commerce-finance', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (25, 'management-business', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (26, 'government-civil-services', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (26, 'banking-insurance', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (26, 'education-teaching', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (27, 'entrepreneurship', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (27, 'design-creative', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (27, 'media-communication', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (28, 'emerging-careers', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (29, 'it-software', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (29, 'emerging-careers', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (30, 'hospitality-tourism', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (30, 'sports-fitness', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (31, 'agriculture', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (31, 'skilled-trades', 1);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (32, 'management-business', 2);
INSERT INTO assessment_option_weights (option_id, category_slug, weight) VALUES (32, 'banking-insurance', 1);
